name: portfolio5
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.5
  flutter: 3.10.5

dependencies:
  flutter:
    sdk: flutter

  characters: 1.3.0
  flutter_svg: 2.0.7
  go_router: 9.0.0
  http: 1.1.0
  url_launcher: 6.1.11
  provider: 6.0.5
  equatable: 2.0.5
  json_annotation: 4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # fvm flutter pub run build_runner build --delete-conflicting-outputs
  build_runner: 2.4.5
  flutter_lints: 2.0.1
  json_serializable: 6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/languages/
    - assets/icons/social/
    - assets/icons/technologies/

  fonts:
    - family: CPMono
      fonts:
        - asset: assets/fonts/CPMono.otf
    - family: Kontanter
      fonts:
        - asset: assets/fonts/Kontanter.otf
    - family: Prime
      fonts:
        - asset: assets/fonts/Prime.otf
