name: Test passphrase

on:
  push:
    branches:
      # put random stuff to block
      - 'skdjhfksdfhsldkflsd'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Only works with v2

      # encrypt with: gpg --symmetric --cipher-algo AES256 lib/config.dart
      - name: decrypt
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output lib/config.dart lib/config.dart.gpg
        env:
          PASSPHRASE: ${{secrets.CONFIG_PASSPHRASE}}
