name: Test passphrase

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Only works with v2

      - name: decrypt
        run: gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" --output lib/config.dart lib/config.dart.gpg
        env:
          PASSPHRASE: ${{secrets.CONFIG_PASSPHRASE}}
